use super::Quantity;

table! {
    #[doc = "A table of constants relevant to rendering mathematics."]
    pub Constants { // MathConstants
        script_percent_scale_down                     (i16     ),
        script_script_percent_scale_down              (i16     ),
        delimited_sub_formula_min_height              (u16     ),
        display_operator_min_height                   (u16     ),
        math_leading                                  (Quantity),
        axis_height                                   (Quantity),
        accent_base_height                            (Quantity),
        flattened_accent_base_height                  (Quantity),
        subscript_shift_down                          (Quantity),
        subscript_top_max                             (Quantity),
        subscript_baseline_drop_min                   (Quantity),
        superscript_shift_up                          (Quantity),
        superscript_shift_up_cramped                  (Quantity),
        superscript_bottom_min                        (Quantity),
        superscript_baseline_drop_max                 (Quantity),
        sub_superscript_gap_min                       (Quantity),
        superscript_bottom_max_with_subscript         (Quantity),
        space_after_script                            (Quantity),
        upper_limit_gap_min                           (Quantity),
        upper_limit_baseline_rise_min                 (Quantity),
        lower_limit_gap_min                           (Quantity),
        lower_limit_baseline_drop_min                 (Quantity),
        stack_top_shift_up                            (Quantity),
        stack_top_display_style_shift_up              (Quantity),
        stack_bottom_shift_down                       (Quantity),
        stack_bottom_display_style_shift_down         (Quantity),
        stack_gap_min                                 (Quantity),
        stack_display_style_gap_min                   (Quantity),
        stretch_stack_top_shift_up                    (Quantity),
        stretch_stack_bottom_shift_down               (Quantity),
        stretch_stack_gap_above_min                   (Quantity),
        stretch_stack_gap_below_min                   (Quantity),
        fraction_numerator_shift_up                   (Quantity),
        fraction_numerator_display_style_shift_up     (Quantity),
        fraction_denominator_shift_down               (Quantity),
        fraction_denominator_display_style_shift_down (Quantity),
        fraction_numerator_gap_min                    (Quantity),
        fraction_num_display_style_gap_min            (Quantity),
        fraction_rule_thickness                       (Quantity),
        fraction_denominator_gap_min                  (Quantity),
        fraction_denom_display_style_gap_min          (Quantity),
        skewed_fraction_horizontal_gap                (Quantity),
        skewed_fraction_vertical_gap                  (Quantity),
        overbar_vertical_gap                          (Quantity),
        overbar_rule_thickness                        (Quantity),
        overbar_extra_ascender                        (Quantity),
        underbar_vertical_gap                         (Quantity),
        underbar_rule_thickness                       (Quantity),
        underbar_extra_descender                      (Quantity),
        radical_vertical_gap                          (Quantity),
        radical_display_style_vertical_gap            (Quantity),
        radical_rule_thickness                        (Quantity),
        radical_extra_ascender                        (Quantity),
        radical_kern_before_degree                    (Quantity),
        radical_kern_after_degree                     (Quantity),
        radical_degree_bottom_raise_percent           (i16     ),
    }
}