use super::ValueRecord;

table! {
    #[doc = "A table of constants relevant to rendering mathematics."]
    pub Constants { // MathConstants
        script_percent_scale_down                     (i16        ),
        script_script_percent_scale_down              (i16        ),
        delimited_sub_formula_min_height              (u16        ),
        display_operator_min_height                   (u16        ),
        math_leading                                  (ValueRecord),
        axis_height                                   (ValueRecord),
        accent_base_height                            (ValueRecord),
        flattened_accent_base_height                  (ValueRecord),
        subscript_shift_down                          (ValueRecord),
        subscript_top_max                             (ValueRecord),
        subscript_baseline_drop_min                   (ValueRecord),
        superscript_shift_up                          (ValueRecord),
        superscript_shift_up_cramped                  (ValueRecord),
        superscript_bottom_min                        (ValueRecord),
        superscript_baseline_drop_max                 (ValueRecord),
        sub_superscript_gap_min                       (ValueRecord),
        superscript_bottom_max_with_subscript         (ValueRecord),
        space_after_script                            (ValueRecord),
        upper_limit_gap_min                           (ValueRecord),
        upper_limit_baseline_rise_min                 (ValueRecord),
        lower_limit_gap_min                           (ValueRecord),
        lower_limit_baseline_drop_min                 (ValueRecord),
        stack_top_shift_up                            (ValueRecord),
        stack_top_display_style_shift_up              (ValueRecord),
        stack_bottom_shift_down                       (ValueRecord),
        stack_bottom_display_style_shift_down         (ValueRecord),
        stack_gap_min                                 (ValueRecord),
        stack_display_style_gap_min                   (ValueRecord),
        stretch_stack_top_shift_up                    (ValueRecord),
        stretch_stack_bottom_shift_down               (ValueRecord),
        stretch_stack_gap_above_min                   (ValueRecord),
        stretch_stack_gap_below_min                   (ValueRecord),
        fraction_numerator_shift_up                   (ValueRecord),
        fraction_numerator_display_style_shift_up     (ValueRecord),
        fraction_denominator_shift_down               (ValueRecord),
        fraction_denominator_display_style_shift_down (ValueRecord),
        fraction_numerator_gap_min                    (ValueRecord),
        fraction_num_display_style_gap_min            (ValueRecord),
        fraction_rule_thickness                       (ValueRecord),
        fraction_denominator_gap_min                  (ValueRecord),
        fraction_denom_display_style_gap_min          (ValueRecord),
        skewed_fraction_horizontal_gap                (ValueRecord),
        skewed_fraction_vertical_gap                  (ValueRecord),
        overbar_vertical_gap                          (ValueRecord),
        overbar_rule_thickness                        (ValueRecord),
        overbar_extra_ascender                        (ValueRecord),
        underbar_vertical_gap                         (ValueRecord),
        underbar_rule_thickness                       (ValueRecord),
        underbar_extra_descender                      (ValueRecord),
        radical_vertical_gap                          (ValueRecord),
        radical_display_style_vertical_gap            (ValueRecord),
        radical_rule_thickness                        (ValueRecord),
        radical_extra_ascender                        (ValueRecord),
        radical_kern_before_degree                    (ValueRecord),
        radical_kern_after_degree                     (ValueRecord),
        radical_degree_bottom_raise_percent           (i16        ),
    }
}