name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with: {toolchain: stable, components: clippy, rustfmt}
      - run: cargo clippy -- -D warnings
      - run: cargo fmt --all -- --check

  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        features: [all, no-default]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with: {toolchain: stable}
      - run: cargo test --${{ matrix.features }}-features
